-- breaktheice 시퀀스 삭제 명령어
DROP SEQUENCE CHAT_SEQ; 
DROP SEQUENCE INTEREST_SEQ; 
DROP SEQUENCE MEET_SEQ; 
DROP SEQUENCE MEMBER_SEQ; 
DROP SEQUENCE MESSAGE_SEQ; 
DROP SEQUENCE POST_SEQ; 
DROP SEQUENCE POST_TYPE_SEQ; 
DROP SEQUENCE REPLY_SEQ; 
DROP SEQUENCE ROLE_SEQ; 
DROP SEQUENCE TEAM_SEQ; 

-- 샘플테이블은 삭제 진행하지 않았습니다.
-- breaktheice  테이블 삭제 명령어
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "INTEREST" CASCADE CONSTRAINTS;
DROP TABLE "TEAM" CASCADE CONSTRAINTS;
DROP TABLE "POST_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "POST" CASCADE CONSTRAINTS;
DROP TABLE "REPLY" CASCADE CONSTRAINTS;
DROP TABLE "ROLE" CASCADE CONSTRAINTS;
DROP TABLE "MEET" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_ROLE" CASCADE CONSTRAINTS;
DROP TABLE "TEAM_POST" CASCADE CONSTRAINTS;
DROP TABLE "CHAT" CASCADE CONSTRAINTS;
DROP TABLE "TEAM_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;
DROP TABLE "MEET_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "MEMBER_INTEREST" CASCADE CONSTRAINTS;
DROP TABLE "POST_REPLY" CASCADE CONSTRAINTS;
DROP TABLE "TEAM_REPLY" CASCADE CONSTRAINTS;
DROP TABLE "TEAM_POST_REPLY" CASCADE CONSTRAINTS;
DROP TABLE "ATTACH" CASCADE CONSTRAINTS;


